### pip install <package name> - similar to install.packages in R

### import <package name> as <alias> eg; import numpy as np similar to library(package_name) in R

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a2=np.array([[1,2,3,5],[5,6,7,8],[9,10,11,12]])
a2

array([[ 1,  2,  3,  5],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# image classifcation - car - as an image is passed as an input - image 1080*690*RGBA - 2*2 dimensions 

### Initialize an array with zeroes

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(5,10,15)

array([ 5.        ,  5.35714286,  5.71428571,  6.07142857,  6.42857143,
        6.78571429,  7.14285714,  7.5       ,  7.85714286,  8.21428571,
        8.57142857,  8.92857143,  9.28571429,  9.64285714, 10.        ])

In [14]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [15]:
np.random.random((3,4))

array([[0.61393976, 0.38105167, 0.22403179, 0.94011164],
       [0.33209763, 0.75010067, 0.25332358, 0.49923644],
       [0.24374208, 0.13447777, 0.49884523, 0.61973229]])

In [16]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [17]:
a.shape=(3,2)

In [18]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
a.shape=(6,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [80]:
b=np.arange(10)

In [81]:
b.shape

(10,)

In [82]:
b.shape=(5,2)

In [25]:
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
b.size

10

In [28]:
a.shape

(6, 1)

In [29]:
c=np.array(['a','b','c'])

In [30]:
print(c)

['a' 'b' 'c']


In [31]:
c.dtype

dtype('<U1')

In [32]:
a.dtype

dtype('int64')

In [33]:
np.sum([10,20])

30

In [34]:
a,b=10,15
np.sum([a,b])

25

In [35]:
np.sum([[1,2,3],[4,5,6]])

21

In [37]:
np.sum([[1,2,3],[4,5,6]],axis=0) # axis=0 - Col wise Addition

array([5, 7, 9])

In [39]:
np.sum([[1,2,3],[4,5,6]],axis=1) # Row wise Addition

array([ 6, 15])

In [40]:
a=[1,2,3]
b=[1,3,4]
c=[1,2,3]
np.equal(a,b) # - Element wise Comparison

array([ True, False, False])

In [41]:
np.equal(a,c)

array([ True,  True,  True])

In [42]:
np.array_equal(a,b) # - Array wise Comparison

False

In [43]:
np.array_equal(a,c)

True

In [44]:
# np.sum, np.mean,np.min, np.max, np.median, np.std, 

### indexing and slicing of data 

In [46]:
a=['T','h','i','s',' ','i','s',' ','p','y','t','h','o','n']
a[5]

'i'

In [48]:
a[-10]

' '

In [65]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
a[:1]

array([[1, 2, 3]])

In [68]:
a[:2,2:]

array([[3],
       [6]])

In [ ]:
# :N in the first dimension is a row wise. include only n-1 rows
#:N in the second dimension is a col wise. include only n-1 columns
# N: in the first dimension is a row wise. exclude only n-1 rows
# N: in the second dimension is a col wise. exlude only n-1 columns

In [52]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [53]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [55]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [56]:
# Stack array row wise
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
a=np.arange(16).reshape(4,4)

In [59]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [60]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [61]:
list1=[1,2,3,4]

In [62]:
list1

[1, 2, 3, 4]

In [63]:
import sys
b=range(1000) # range(1,1000) in R
print('size of a list: ',sys.getsizeof(b)*len(b))
a=np.arange(1000)
print('size of an array: ',a.size * a.itemsize)

size of a list:  48000
size of an array:  8000


In [69]:
# np.reshape, np.sum, slicing and indexing 

In [70]:
a=np.arange(24).reshape(6,4)

In [71]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [76]:
a.reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# mostly used methods in numpy
1. arange
2. random.random
3. reshape
4. size
5. indexing
6. Slicing - important
7. np.array
